-- MySQL Script generated by MySQL Workbench
-- qua 30 abr 2025 09:46:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaria` ;
USE `pizzaria` ;

-- -----------------------------------------------------
-- Table `pizzaria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pizza` (
  `idpizza` INT NOT NULL AUTO_INCREMENT,
  `variedade` VARCHAR(45) NOT NULL,
  `tamanho` VARCHAR(7) NOT NULL,
  `preso` DECIMAL(10,2) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idpizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`bebidas` (
  `idbebidas` INT NOT NULL AUTO_INCREMENT,
  `variedade` VARCHAR(45) NOT NULL,
  `l_ml` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idbebidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`feedback` (
  `idfeedback` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfeedback`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedito` (
  `idpedito` INT NOT NULL AUTO_INCREMENT,
  `pizza_idpizza` INT NOT NULL,
  `bebidas_idbebidas` INT NOT NULL,
  `feedback_idfeedback` INT NOT NULL,
  PRIMARY KEY (`idpedito`),
  INDEX `fk_pedito_pizza1_idx` (`pizza_idpizza` ASC) VISIBLE,
  INDEX `fk_pedito_bebidas1_idx` (`bebidas_idbebidas` ASC) VISIBLE,
  INDEX `fk_pedito_feedback1_idx` (`feedback_idfeedback` ASC) VISIBLE,
  CONSTRAINT `fk_pedito_pizza1`
    FOREIGN KEY (`pizza_idpizza`)
    REFERENCES `pizzaria`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedito_bebidas1`
    FOREIGN KEY (`bebidas_idbebidas`)
    REFERENCES `pizzaria`.`bebidas` (`idbebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedito_feedback1`
    FOREIGN KEY (`feedback_idfeedback`)
    REFERENCES `pizzaria`.`feedback` (`idfeedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT(3) NOT NULL,
  `indereco` VARCHAR(45) NOT NULL,
  `fone` INT NOT NULL,
  `pedito_idpedito` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_pedito1_idx` (`pedito_idpedito` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_pedito1`
    FOREIGN KEY (`pedito_idpedito`)
    REFERENCES `pizzaria`.`pedito` (`idpedito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`delivery` (
  `iddelivery` INT NOT NULL AUTO_INCREMENT,
  `endereco_entrega` VARCHAR(45) NOT NULL,
  `form_pagamento` DECIMAL(10,2) NOT NULL,
  `tempo_entrega` VARCHAR(45) NOT NULL,
  `pedito_idpedito` INT NOT NULL,
  PRIMARY KEY (`iddelivery`),
  INDEX `fk_delivery_pedito1_idx` (`pedito_idpedito` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_pedito1`
    FOREIGN KEY (`pedito_idpedito`)
    REFERENCES `pizzaria`.`pedito` (`idpedito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`entregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`entregado` (
  `identregado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `marca_moto` VARCHAR(45) NOT NULL,
  `delivery_iddelivery` INT NOT NULL,
  PRIMARY KEY (`identregado`),
  INDEX `fk_entregado_delivery1_idx` (`delivery_iddelivery` ASC) VISIBLE,
  CONSTRAINT `fk_entregado_delivery1`
    FOREIGN KEY (`delivery_iddelivery`)
    REFERENCES `pizzaria`.`delivery` (`iddelivery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`preco` (
  `idpreco` INT NOT NULL AUTO_INCREMENT,
  `idpizza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpreco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`ingredientes` (
  `idingredientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idingredientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`ingredientes_has_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`ingredientes_has_pizza` (
  `ingredientes_idingredientes` INT NOT NULL,
  PRIMARY KEY (`ingredientes_idingredientes`),
  INDEX `fk_ingredientes_has_pizza_ingredientes1_idx` (`ingredientes_idingredientes` ASC) VISIBLE,
  CONSTRAINT `fk_ingredientes_has_pizza_ingredientes1`
    FOREIGN KEY (`ingredientes_idingredientes`)
    REFERENCES `pizzaria`.`ingredientes` (`idingredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pagamento` (
  `idpagamento` INT NOT NULL,
  `form_pagamento` VARCHAR(45) NOT NULL,
  `quantidade` DECIMAL(10,2) NOT NULL,
  `pedito_idpedito` INT NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_pagamento_pedito1_idx` (`pedito_idpedito` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_pedito1`
    FOREIGN KEY (`pedito_idpedito`)
    REFERENCES `pizzaria`.`pedito` (`idpedito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`cardapio` (
  `idcardapio` INT NOT NULL,
  `combo` VARCHAR(45) NULL,
  `rodizio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcardapio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`estoque` (
  `idestoque` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `limite` VARCHAR(45) NOT NULL,
  `ingredientes_idingredientes` INT NOT NULL,
  `bebidas_idbebidas` INT NOT NULL,
  PRIMARY KEY (`idestoque`),
  INDEX `fk_estoque_ingredientes1_idx` (`ingredientes_idingredientes` ASC) VISIBLE,
  INDEX `fk_estoque_bebidas1_idx` (`bebidas_idbebidas` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_ingredientes1`
    FOREIGN KEY (`ingredientes_idingredientes`)
    REFERENCES `pizzaria`.`ingredientes` (`idingredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_bebidas1`
    FOREIGN KEY (`bebidas_idbebidas`)
    REFERENCES `pizzaria`.`bebidas` (`idbebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`ingredientes_has_pizza_has_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`ingredientes_has_pizza_has_pizza` (
  `ingredientes_has_pizza_ingredientes_idingredientes` INT NOT NULL,
  `pizza_idpizza` INT NOT NULL,
  PRIMARY KEY (`ingredientes_has_pizza_ingredientes_idingredientes`, `pizza_idpizza`),
  INDEX `fk_ingredientes_has_pizza_has_pizza_pizza1_idx` (`pizza_idpizza` ASC) VISIBLE,
  INDEX `fk_ingredientes_has_pizza_has_pizza_ingredientes_has_pizza1_idx` (`ingredientes_has_pizza_ingredientes_idingredientes` ASC) VISIBLE,
  CONSTRAINT `fk_ingredientes_has_pizza_has_pizza_ingredientes_has_pizza1`
    FOREIGN KEY (`ingredientes_has_pizza_ingredientes_idingredientes`)
    REFERENCES `pizzaria`.`ingredientes_has_pizza` (`ingredientes_idingredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredientes_has_pizza_has_pizza_pizza1`
    FOREIGN KEY (`pizza_idpizza`)
    REFERENCES `pizzaria`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`ingre_pizza1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`ingre_pizza1` (
  `ingre_idingre` INT NOT NULL,
  `pizza_idpizza` INT NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ingre_idingre`, `pizza_idpizza`),
  INDEX `fk_ingredientes_has_pizza1_pizza1_idx` (`pizza_idpizza` ASC) VISIBLE,
  INDEX `fk_ingredientes_has_pizza1_ingredientes1_idx` (`ingre_idingre` ASC) VISIBLE,
  CONSTRAINT `fk_ingredientes_has_pizza1_ingredientes1`
    FOREIGN KEY (`ingre_idingre`)
    REFERENCES `pizzaria`.`ingredientes` (`idingredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredientes_has_pizza1_pizza1`
    FOREIGN KEY (`pizza_idpizza`)
    REFERENCES `pizzaria`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`promoçoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`promoçoes` (
  `idpromoçoes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL,
  `vantagem` VARCHAR(45) NOT NULL,
  `pizza_idpizza` INT NOT NULL,
  `bebidas_idbebidas` INT NOT NULL,
  PRIMARY KEY (`idpromoçoes`),
  INDEX `fk_promoçoes_pizza1_idx` (`pizza_idpizza` ASC) VISIBLE,
  INDEX `fk_promoçoes_bebidas1_idx` (`bebidas_idbebidas` ASC) VISIBLE,
  CONSTRAINT `fk_promoçoes_pizza1`
    FOREIGN KEY (`pizza_idpizza`)
    REFERENCES `pizzaria`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promoçoes_bebidas1`
    FOREIGN KEY (`bebidas_idbebidas`)
    REFERENCES `pizzaria`.`bebidas` (`idbebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
